### ISSUE TITLE
More realistic digi parameters

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMX-Software/Ecal#21]
Some of the current digi parameters are far from realistic. I just want to get the closer to realism and this is just a reminder of what needs to change.

Parameter | Old Value | New Value
---|---|---
Readout Capacitance (pF) | 0.1 | 20

**Comment by tomeichlersmith** [comment]
This issue will also deal with separating the DIGI and RECO parameters from one another. They can't be related to one another in the data pipeline, so they shouldn't be related to one another in the sim pipeline.

**Comment by tomeichlersmith** [comment]
After discussion on https://github.com/LDMX-Software/ldmx-sw/issues/932 and slack, we have committed to fixing this ECal reconstruction offset before the v2.3 release. I am putting this work here along with some other small tasks that will help me fix up the ECal digi pipeline.

**Comment by tomeichlersmith** [comment]
@omar-moreno @jmmans @vdutta Moving this here because it is ECal-centric.

[Looking at the pulse shape that is coded in the simulation](https://www.desmos.com/calculator/zp4aojmy8s), it is _very sharp_. This lends evidence to my theory that since we are only taking the maximum number of ADC counts (during ADC mode) instead of the actual amplitude, we can "miss" a lot of the charge/voltage/energy only through our measurement process.
To remedy this, the first thing I'm going to do is implement a time-shift such that we measure the digis at a time that is
(distance from particle gun to ECal)/(speed of light). Hopefully, this will get our ADC peaks closer to the sampling time and rectify this issue. The downside of this approach is that we _need_ to use the gun fired from far upstream, so that the ECal digis are configured properly. A longer term solution would be configuring all particle guns such that the primary electron arrive{s,d} at the target at Geant4 global time = 0. This would require some massaging in the simulation side, but shouldn't be too hard.

**Comment by jmmans** [comment]
Dear Tom,

The "right" solution is to add a little more realism here.  The 
effective response of the system includes a shaping term of the 
preamplifier.  This behaves like convolving the fast pulse shape with a 
Gaussian of full width ~20ns.

Jeremy

**Comment by tomeichlersmith** [comment]
Woof - okay, does it make more sense to add this convolution to the HgcrocEmulator (so that Hcal uses it too?) or should I try to do this convolution within ECal?
I guess my plan would be to do it inside the emulator because I'm assuming Hcal would benefit from the convolution as well.

**Comment by jmmans** [comment]
Dear Tom,

Looking at your plot, this isn't "really sharp".  It's what I would 
expect and contains the shaping term I talked about.

It's true that all the ECAL planes (and HCAL planes) will need to be 
adjusted for the TOF and other effects.

Jeremy

**Comment by tomeichlersmith** [comment]
Yea, doing some back of the napkin math led me to using T~0.8ns for the front of the ECal which still means the measurment at t=0. is within 1% of the max amplitude. I'm going to keep searching...

**Comment by tomeichlersmith** [comment]
I found an issue!

When I lower the relative error down to 2.5% (from 5%), I get failures in the early TOT range. More investigation to come...

**Comment by tomeichlersmith** [comment]
Update: Found some mishandling of the TOT threshold and now there are only three energies where the sim and the recon energy have a relative difference above 2.5%.

**Comment by vdutta** [comment]
@tomeichlersmith was this issue with the TOT threshold also what was causing the offset for low energies (< 10 MeV)? Or is that a separate issue?

**Comment by tomeichlersmith** [comment]
Yes - before fixing up the TOT threshold, I was getting rec energys in the 6-12MeV range that were uniformly lower than the sim energy by several percent. Summed together, this would account for the overal shift (especially after applying the layer weights which scales everything up). Please re-run ecal reco to double check my work (that's why I asked for your review in all honesty).

**Comment by tomeichlersmith** [comment]
Here's how the TP Estimated Energies and the Reconstructed Energies compare to the input simulated energies.
![RecEnergy_vs_SimEnergy](https://user-images.githubusercontent.com/31970302/98156169-0c4cf180-1e9d-11eb-8546-0d5881f62755.png)
![TPEstEnergy_vs_SimEnergy](https://user-images.githubusercontent.com/31970302/98156171-0ce58800-1e9d-11eb-8b21-4d6fe56566f8.png)
