### ISSUE TITLE
Ecal veto input collection name should be configurable 

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/Ecal#22]
In light of the pileup overlay work, where the resulting (overlay) collection can't have the same name as the input simhit collection, we need to be able to steer the BDT (or other Ecal veto algorithms) to the overlay collection rather than `EcalSimHit`. 

This will be used as part of overlay validation (obviously the veto itself will have to be retrained, but the first step is to verify that it runs as expected on the pileup overlay collections).

**Comment by bryngemark** [comment]
This is in fact not fixed yet. Only the pass name has been made configurable; the name of the input collection is still hardwired to `EcalRecHits`. Was this a conscious choice?

**Comment by tomeichlersmith** [comment]
Nope! Must have gotten lost in the shuffle of rebases. Do you have a fix on some branch? Otherwise, I can implement one pretty easily.

**Comment by bryngemark** [comment]
I don't, so if you don't mind putting it in (as you're probably more likely to anyway be doing something Ecal related) that would be helpful :)

**Comment by tomeichlersmith** [comment]
Since this was such a small change, I've pushed it up to trunk of this repo and opened a PR to update the submodule ref on ldmx-sw: https://github.com/LDMX-Software/ldmx-sw/pull/954
