### ISSUE TITLE
Make the EcalRecHits collection name in the veto processor configurable

### ISSUE THREAD

**Issue by p-masterson** [LDMX-Software/Ecal#38]
Currently, the EcalRecHits branch passed to the EcalVeto must start with the string "EcalRecHits_" (see lines 299-300).  For multielectron configs that need to run multiple veto passes on different collections of EcalRecHits, this constraint can be hard to work around--in particular, it's convenient to name the overlay collection something else like "EcalRecHitsOverlay_..." to prevent EcalVeto from getting confused by multiple similar branch names.

Lene and I were unable to find a way to fix this in the configs alone.  However, making the EcalRecHits pass name a  configurable parameter would make this easy to solve.

From what I can tell, this should be an easy fix, and I'll hopefully be able to get it done sometime in the next few days.

(Alternatively, if there's an existing way to work around this problem in the config script alone, let me know!)

**Comment by p-masterson** [comment]
Apparently this was just a one-line change:  rec_pass_name_ had already been defined in EcalVetoProcessor.cxx, but was not being used.  I've pushed the change to the new config-rec-hits branch.

**Comment by tomeichlersmith** [comment]
:+1: I merged in this simple change to Ecal/trunk. It will get picked up into ldmx-sw/trunk next time we update the Ecal submodule ref.
