### ISSUE TITLE
Some veto variables are no longer calculated in reconstruction

### ISSUE THREAD

**Issue by bryngemark** [LDMX-Software/Ecal#46]
Since at least v3.2.0, there are no containment variables, recoil electron px/y/z, etc being calculated for signal and I can't see that there are any reconstruction differences at the config level between signal and e.g. Ecal PN, which does have them. Please prove me wrong but this looks like a bug.

**Comment by bryngemark** [comment]
For instance I wonder if this is still true: 
https://github.com/LDMX-Software/ldmx-sw/blob/71d0552208bcbaf499478932feb382a7141c89cf/Tools/src/Tools/AnalysisUtils.cxx#L31
... I have a feeling there might have been subtle changes to signal generation lately.

**Comment by bryngemark** [comment]
I suppose @tomeichlersmith might be the person to ask about that

**Comment by tomeichlersmith** [comment]
Yep :face_with_head_bandage: the recoil electron no longer always as track ID == 1.

We will need to update that function to search the particle map for the electron whose creator processes is eDarkBrem. e.g.

https://github.com/LDMX-Software/ldmx-analysis/blob/5daa769dbdd190857a0c3422a330a0f75cc765b2/src/Analysis/EaT/DarkBremKinematics.cxx#L120-L122

**Comment by tomeichlersmith** [comment]
Resolved by https://github.com/LDMX-Software/ldmx-sw/pull/1154
